language: node_js
node_js:
  - "node"
cache: npm
addons:
  apt:
    update: true
    packages:
      - sqlite3

services:
  # Use docker for the databases, so that we can support Microsoft SQL Server in the tests.
  - docker

env:
  - SQLITE=y

  # Docker-based database settings.
  # These values are based on the docker-compose parameters.
  - MYSQL_DB=tern
  - MYSQL_USERNAME=tern-user
  - MYSQL_PASSWORD=tern-pw
  - MYSQL_PORT=19000

  - POSTGRES_DB=tern
  - POSTGRES_USERNAME=tern-user
  - POSTGRES_PASSWORD=tern-pw
  - POSTGRES_PORT=19001

  - MSSQL_DB=master
  - MSSQL_USERNAME=sa
  - MSSQL_PASSWORD=tern-pw-1234
  - MSSQL_PORT=19002


#before_install:

install:
  - npm install
  - npm run bootstrap
  - docker-compose -f packages/datastore-sql/docker-tests/docker-compose.yml up

jobs:
  include:
    - stage: "Build"
      name: "TypeScript Compile"
      script: "npm run build"
    - stage: "Test"
      name: "Unit Tests"
      script: "npm run test"

